# Site settings
title: "Friends of the Park of Windcrest, Texas"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Friends of the Park of Windcrest, Texas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://windcrestfotp.com" # the base hostname & protocol for your site
twitter_username: WindcrestFOTP
github_username: FriendsoftheParkofWindcrestTexas
paginator: 5
# Build settings
markdown: kramdown
permalink: pretty
